image: node:lts-buster

pages:
  stage: deploy
  script:
    - npm install
    - npm run build
    - cp -r dist public
  tags:
    - build
  artifacts:
    paths:
      - public
  only:
    refs:
      - master
